import Link from "next/link";
import BrandLogo from "@/components/BrandLogo";

export const metadata = { title: "Terms of Service — Repra" };

const EFFECTIVE_DATE = "August 28, 2026";
const CONTACT_EMAIL = "billy.e.riley@gmail.com";

export default function TermsPage() {
  return (
    <div className="max-w-xl mx-auto min-h-screen flex flex-col px-5 py-8">
      <div className="mb-6">
        <BrandLogo className="h-6 w-auto" />
      </div>

      <h1 className="font-display text-3xl leading-none mb-1">Terms of Service</h1>
      <p className="font-label text-xs text-[var(--muted)] mb-6">Effective {EFFECTIVE_DATE}</p>

      <div className="card flex flex-col gap-5 text-[13px] leading-relaxed text-[var(--chalk-dim)]">
        <p>
          Repra is operated by Billy Riley, an individual (&quot;<strong className="text-[var(--chalk)]">we</strong>&quot;,
          &quot;<strong className="text-[var(--chalk)]">us</strong>&quot;). These Terms of Service (&quot;Terms&quot;) govern
          your access to and use of Repra (the &quot;Service&quot;). By creating an account or using the Service, you agree
          to these Terms. If you don&apos;t agree, don&apos;t use the Service.
        </p>

        <Section title="1. Eligibility">
          <p>
            You must be at least 16 years old to use Repra. By using the Service you represent that you meet this
            requirement and that any information you provide is accurate.
          </p>
        </Section>

        <Section title="2. Your Account">
          <p>
            You&apos;re responsible for maintaining the confidentiality of your login credentials and for all activity
            under your account. Tell us right away if you suspect unauthorized access. You can create an account with
            an email and password, or via Google sign-in.
          </p>
        </Section>

        <Section title="3. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc list-outside pl-5 mt-2 flex flex-col gap-1">
            <li>Use the Service for any unlawful purpose or in violation of these Terms;</li>
            <li>Impersonate another person or misrepresent your affiliation with anyone;</li>
            <li>Upload content that&apos;s abusive, harassing, obscene, or infringes someone else&apos;s rights;</li>
            <li>Attempt to interfere with, disrupt, or gain unauthorized access to the Service or its infrastructure;</li>
            <li>Scrape, reverse-engineer, or resell the Service without our written permission.</li>
          </ul>
        </Section>

        <Section title="4. Your Content">
          <p>
            You retain ownership of the workout logs, measurements, photos, and other content you submit
            (&quot;<strong className="text-[var(--chalk)]">User Content</strong>&quot;). By submitting User Content, you
            grant us a non-exclusive, worldwide, royalty-free license to host, store, and display it back to you (and,
            for anything you mark visible on your public profile, to other users) solely to operate and improve the
            Service. You&apos;re responsible for the accuracy and legality of what you submit.
          </p>
        </Section>

        <Section title="5. Not Medical Advice">
          <p>
            Repra is a fitness-tracking tool, not a medical device or a substitute for professional medical, dietary,
            or fitness advice. Talk to a physician before starting any exercise or nutrition program, especially if
            you have an existing condition. You assume all risk associated with physical activity you undertake based
            on information logged in or suggested by the Service. We are not liable for injury, illness, or other harm
            arising from your use of the Service or reliance on anything it displays.
          </p>
        </Section>

        <Section title="6. AI-Generated Content">
          <p>
            Some features (for example, the &quot;Insights&quot; and &quot;Coach&apos;s Take&quot; summaries) are
            generated by a third-party AI model based on your training data. AI-generated content may be inaccurate,
            incomplete, or inappropriate for your specific circumstances. It is not professional advice, and you
            should use your own judgment — and consult a qualified professional where appropriate — before acting on
            it.
          </p>
        </Section>

        <Section title="7. Third-Party Services">
          <p>
            The Service relies on third-party providers to operate — including Google (sign-in and AI processing),
            Neon (database hosting), and Vercel (application hosting and file storage). Your use of Google sign-in is
            also subject to Google&apos;s own terms and privacy policy. See our{" "}
            <Link href="/privacy" className="text-[var(--chalk)] underline">Privacy Policy</Link> for more on how data
            moves through these providers.
          </p>
        </Section>

        <Section title="8. Termination">
          <p>
            You may stop using the Service and request account deletion at any time (see the Privacy Policy for how).
            We may suspend or terminate your access if you violate these Terms or if we discontinue the Service, with
            or without notice, at our discretion.
          </p>
        </Section>

        <Section title="9. Disclaimer of Warranties">
          <p>
            THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE,&quot; WITHOUT WARRANTIES OF ANY KIND,
            EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE
            DON&apos;T GUARANTEE THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT ANY DATA (INCLUDING
            YOUR WORKOUT HISTORY) WILL NEVER BE LOST.
          </p>
        </Section>

        <Section title="10. Limitation of Liability">
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
            CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, PROFITS, OR GOODWILL, ARISING FROM YOUR USE OF
            THE SERVICE, EVEN IF WE&apos;VE BEEN ADVISED OF THE POSSIBILITY. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING
            FROM THE SERVICE WILL NOT EXCEED $100.
          </p>
        </Section>

        <Section title="11. Indemnification">
          <p>
            You agree to indemnify and hold us harmless from any claims, damages, or expenses (including reasonable
            legal fees) arising from your use of the Service, your User Content, or your violation of these Terms.
          </p>
        </Section>

        <Section title="12. Changes to These Terms">
          <p>
            We may update these Terms from time to time. If we make material changes, we&apos;ll update the effective
            date above. Continuing to use the Service after changes take effect means you accept the updated Terms.
          </p>
        </Section>

        <Section title="13. Governing Law">
          <p>
            These Terms are governed by the laws of the State of Delaware, without regard to conflict-of-law
            principles. Any dispute arising from these Terms or the Service will be resolved in the state or federal
            courts located in Delaware, and you consent to that jurisdiction.
          </p>
        </Section>

        <Section title="14. Contact">
          <p>
            Questions about these Terms? Email{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-[var(--chalk)] underline">{CONTACT_EMAIL}</a>.
          </p>
        </Section>
      </div>

      <p className="text-center font-label text-xs text-[var(--muted)] mt-6">
        <Link href="/auth/sign-up" className="text-[var(--chalk)] underline">Back to sign up</Link>
      </p>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="section-label mb-2">{title}</div>
      {children}
    </div>
  );
}
